<a href="https://colab.research.google.com/github/KhantPhyo/Machine-Learning-with-Python---Scikit-Learn/blob/main/Sk1_sklearn_modelling_process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#https://www.tutorialspoint.com/scikit_learn/scikit_learn_modelling_process.htm
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier

from sklearn import metrics

from sklearn import preprocessing

In [2]:
#https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html#sklearn.datasets.load_iris
iris = load_iris()
iris.keys()

#type(iris)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

- Feature Matrix:
The feature matrix is denoted by X and represents the input features or attributes of the dataset. Each row in the feature matrix corresponds to an individual data point (e.g., an iris flower), and each column represents a specific feature or attribute.

In the Iris dataset, there are typically four features: sepal length, sepal width, petal length, and petal width. Therefore, the feature matrix X will have four columns, and each row contains the measurements of these features for a single iris flower.

- Feature Names:
The feature names are an array or list of names that describe each of the features in the feature matrix. In the case of the Iris dataset, the feature names typically correspond to the measurements of the sepal and petal of the iris flowers.
The feature names for the Iris dataset are usually as follows:

.Sepal Length (cm)

.Sepal Width (cm)

.Petal Length (cm)

.Petal Width (cm)


In [4]:
X = iris.data

print("X is : ", X)
X.shape
print("Type of x : ", type(X))

X is :  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.

In [ ]:
X.dtype

dtype('float64')

- esponse Vector:
The response vector is denoted by y and represents the target variable or the labels associated with each data point in the dataset. In supervised learning tasks, like classification, the response vector contains the class labels or target values that you want to predict based on the input features.
In the Iris dataset, the response vector y typically contains class labels that represent the species of iris flowers. There are three possible class labels: "setosa," "versicolor," and "virginica."

- Target Names:
The target names are an array or list that provides human-readable labels or names for the possible classes or target values in the response vector. It helps in understanding the meaning of the class labels.
In the case of the Iris dataset, the target names typically correspond to the species of iris flowers. The target names are as follows:

"setosa"

"versicolor"

"virginica"


In [5]:
y = iris.target
y.shape

(150,)

In [ ]:
y.dtype

dtype('int64')

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
feature_names = iris.feature_names
feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
target_names = iris.target_names
target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
print("Feature names:", feature_names)
print("Target names:", target_names)
print("\nFirst 10 rows of X:\n", X[:10])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [ ]:
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

    X_train:
        X_train is a variable that will store the training feature matrix.
        In machine learning, the training feature matrix (X_train) typically contains a subset of the dataset's features (input variables) used to train a model. This subset is used to teach the model how to make predictions based on the available data.

    X_test:
        X_test is a variable that will store the testing feature matrix.
        The testing feature matrix (X_test) contains a separate subset of the dataset's features that are not used during training. These features are used to evaluate the model's performance on unseen data.

    y_train:
        y_train is a variable that will store the training response vector.
        In machine learning, the training response vector (y_train) typically contains the corresponding target values or labels for the data points in the training feature matrix (X_train). It is used to teach the model what it should predict during training.

    y_test:
        y_test is a variable that will store the testing response vector.
        The testing response vector (y_test) contains the target values or labels for the data points in the testing feature matrix (X_test). These target values are used to evaluate the model's predictions on unseen data during testing.

    train_test_split:
        train_test_split is a function from Scikit-Learn that is used to split the dataset into training and testing sets.
        It takes several arguments:
            X: The feature matrix containing all the data points and features.
            y: The response vector containing the corresponding target values or labels.
            test_size: This parameter specifies the proportion of the dataset that should be allocated for testing. In this case, test_size=0.3 means that 30% of the data will be used for testing, and 70% will be used for training.
            random_state: This parameter is used to seed the random number generator, ensuring that the split is reproducible. The same value of random_state will result in the same split each time the code is run.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

In [ ]:
X_train.shape, X_test.shape

((105, 4), (45, 4))

In [ ]:
y_train.shape, y_test.shape

((105,), (45,))

# K-Nearest Neighbors (KNN)
KNN is a supervised machine learning algorithm used for both classification and regression tasks. It's based on the principle that data points with similar features tend to belong to the same class or have similar target values. KNN makes predictions by finding the K-nearest data points (neighbors) to a given test data point in the feature space and using their labels (in the case of classification) or their values (in the case of regression) to make a prediction for the test point.

- classifier_knn: This line of code creates an instance of the KNeighborsClassifier class and assigns it to the variable classifier_knn. This instance will be used to build and train a K-Nearest Neighbors classifier.

- KNeighborsClassifier(n_neighbors=3): This part of the code initializes the K-Nearest Neighbors classifier. Here's what it does:

- KNeighborsClassifier is a class provided by Scikit-Learn for K-Nearest Neighbors classification.
        
- n_neighbors=3 specifies the number of neighbors to consider when making predictions. In this case, n_neighbors=3 means that the algorithm will look at the 3 nearest neighbors when making predictions for a new data point. You can adjust this value depending on your specific problem and dataset.

In [6]:
classifier_knn = KNeighborsClassifier(n_neighbors = 3)
classifier_knn

KNeighborsClassifier(n_neighbors=3)

classifier_knn: This is the instance of the KNeighborsClassifier class that you created earlier, and it represents the KNN classifier that you want to train.

-    .fit(): fit() is a method provided by Scikit-Learn and is used to train a machine learning model. In this case, you are applying it to the KNN classifier.

 -   X_train: This is the training feature matrix, which contains the input features of your training data. It consists of a subset of the dataset's data points and their corresponding features. The KNN classifier will learn from this data to make predictions.

  -  y_train: This is the training response vector, which contains the target values or class labels corresponding to the data points in X_train. It provides the ground truth for the training data, allowing the KNN classifier to learn how to classify or predict based on the input features.

- When you execute classifier_knn.fit(X_train, y_train), the KNN classifier is trained by finding the nearest neighbors in X_train for each data point and learning from their class labels in y_train. The model learns the relationships between the features in X_train and the corresponding target values in y_train. Once training is complete, the KNN classifier is ready to make predictions on new, unseen data points based on the patterns it has learned during training.

In [ ]:
classifier_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

y_pred = classifier_knn.predict(X_test) is used to make predictions using the trained K-Nearest Neighbors (KNN) classifier, and y_pred.shape is used to retrieve the shape or dimensions of the y_pred array. Let's explain each part:

    y_pred = classifier_knn.predict(X_test):
        classifier_knn: This is the trained KNN classifier that you previously fit to the training data using classifier_knn.fit(X_train, y_train). It has learned the relationships between the input features and the target labels during training.
        .predict(): predict() is a method provided by Scikit-Learn for making predictions using a trained machine learning model. In this case, you are using it to make predictions on a set of data points, which is represented by X_test.
        X_test: This is the testing feature matrix containing a subset of the dataset's data points that were not used during training. The KNN classifier will make predictions for these data points based on the patterns it learned during training.
        y_pred: This variable will store the predicted values or labels generated by the KNN classifier for the data points in X_test. Each element of y_pred corresponds to a prediction for a single data point.

    y_pred.shape:
        Once you have made predictions using y_pred, you can check the shape of the y_pred array using the .shape attribute. The shape of an array tells you its dimensions, typically represented as (number of rows, number of columns).
        In the context of y_pred, y_pred.shape will return a tuple that indicates the number of predictions made and, if applicable, the number of output dimensions. For classification tasks, this typically represents the number of data points in the test set and the number of classes or labels.

For example, if you have 100 data points in your test set, and you are performing binary classification (two classes), the shape of y_pred might be (100,). This means you have 100 predictions, one for each data point, and there's only one output dimension for each prediction, representing the predicted class label.

In [ ]:
y_pred = classifier_knn.predict(X_test)
y_pred.shape

(45,)

The code metrics.accuracy_score(y_test, y_pred) is used to calculate the accuracy of a machine learning model's predictions when compared to the true target values. Let's break down this code:

  -  metrics: This refers to the metrics module in Scikit-Learn, which provides various functions for evaluating machine learning model performance.

   - .accuracy_score(): This is a specific function from the metrics module used to calculate the accuracy of a classification model. Accuracy is a common metric used for classification tasks and represents the proportion of correctly classified data points out of all the data points.

-    y_test: This is the true target values or ground truth labels for the test data. It contains the actual correct labels or values that you are trying to predict using your machine learning model.

 -   y_pred: This is the predicted values or labels generated by your machine learning model when applied to the test data. It contains the model's predictions for the test set.

When you execute metrics.accuracy_score(y_test, y_pred), the accuracy_score function compares the predicted labels (y_pred) to the true labels (y_test) and calculates the accuracy as the ratio of correctly predicted labels to the total number of labels in the test set. The result is a single accuracy score that indicates how well the model's predictions match the true values.

Here's what the returned value represents:

  -  The accuracy score is a single number typically between 0 and 1, where 0 represents no correct predictions, and 1 represents all predictions are correct.
   - It quantifies the overall performance of the classification model. A higher accuracy score indicates better performance, while a lower score suggests that the model is making more errors in its predictions.

# Accuracy Scoure should be over 95% for Good.


In [ ]:
metrics.accuracy_score(y_test, y_pred)

0.9777777777777777

In [ ]:
#'sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'
sample = [[5, 5, 3, 2], [2, 4, 3, 5]]
sample

[[5, 5, 3, 2], [2, 4, 3, 5]]

simple date (created) to predict like x-test. And the output result preds is like y-preds.

In [ ]:
#['setosa' 'versicolor' 'virginica']
preds = classifier_knn.predict(sample)
preds

array([1, 2])

print predict value to name using below code.

In [ ]:
[iris.target_names[p] for p in preds]

['versicolor', 'virginica']

In [ ]:
for p in preds:
  print(iris.target_names[p])

versicolor
virginica


Convert the Scikit learn data to excel data ( 2D data frame)

In [3]:
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['target'] = iris.target_names[iris.target]

# Export to Excel
iris_df.to_excel('iris_dataset.xlsx', index=False)
iris_df.head()
#iris_df.dtypes

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa